apiVersion: v1
kind: Service
metadata:
  name: {{ include "ploverdb.fullname" . }}
  namespace: rtx
  labels:
    {{- include "ploverdb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{- include "ploverdb.fullname" .  | nindent 4 }}
